const LOCATION_GET = "LOCATION_GET";
const LOCATION_GET_IP = "LOCATION_GET_IP";
const LOCATION_SET_TO_HISTORY = "LOCATION_SET_TO_HISTORY";
const LOCATION_SET_ERROR = "LOCATION_SET_ERROR";
const LOCATION_SET_ERROR_TYPE = "LOCATION_SET_ERROR_TYPE";
const LOCATION_SET_ERROR_MSG = "LOCATION_SET_ERROR_MSG";

export default {
  LOCATION_GET,
  LOCATION_GET_IP,
  LOCATION_SET_TO_HISTORY,
  LOCATION_SET_ERROR,
  LOCATION_SET_ERROR_TYPE,
  LOCATION_SET_ERROR_MSG
}