const APP_STAGE_SET_CURRENT_LOCATION = "APP_STAGE_SET_CURRENT_LOCATION";
const APP_STAGE_SET_SEARCH_LOCATION = "APP_STAGE_SET_SEARCH_LOCATION"

export default {
  APP_STAGE_SET_CURRENT_LOCATION,
  APP_STAGE_SET_SEARCH_LOCATION
}