const APP_STAGE_SET_CURRENT_LOCATION = "APP_STAGE_SET_CURRENT_LOCATION";
const APP_STAGE_SET_SEARCH_LOCATION = "APP_STAGE_SET_SEARCH_LOCATION";
const APP_DRAWER_TOGGLE = "APP_DRAWER_TOGGLE";

export default {
  APP_STAGE_SET_CURRENT_LOCATION,
  APP_STAGE_SET_SEARCH_LOCATION,
  APP_DRAWER_TOGGLE
}